name: zhaoolee
on:
  schedule:
    - cron:  '0 16 * * *'    # 国际标准时间16点（北京时间凌晨0点），扫描昨天全天文章
  push:
    branches:    
      - main
jobs:
  push:
      runs-on: ${{ matrix.operating-system }}
      strategy:
        matrix:
          # in this example, there is a newer version already installed, 3.7.7, so the older version will be downloaded
          operating-system: ['ubuntu-22.04']
      steps:
      - uses: actions/checkout@v3 # Checking out the repo
      - name: Run with setup-python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          update-environment: false
          cache: 'pipenv'
      - name: Install pipenv
        run: pip3 install --user pipenv
      - name: Install dependecies
        run:  pipenv --python python3 && pipenv install
      - name: Build
        env:
            USER: ${{ secrets.USER }}
            PASSWORD: ${{ secrets.PASSWORD }}
            HOST: ${{ secrets.HOST }}
            EMAIL_LISTS: ${{ secrets.EMAIL_LISTS }}
        run: pipenv run build
      - name: Commit and push if changed   # 更新README.md
        run: |
          git diff
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add README.md docs result.json .seen_links.json
          git commit -m "Github Action auto Updated"
          git push
